import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "AI Todo App",
  description: "Todo App generated by AI",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <main className="p-4">{children}</main>
      </body>
    </html>
  );
}
